# Generated by Django 5.0.1 on 2024-02-12 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralrelationship",
            name="refer_token",
        ),
    ]
