# Generated by Django 5.0.1 on 2024-02-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_referralrelationship_refer_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.BigIntegerField(default=0),
        ),
    ]
