# Generated by Django 5.0.1 on 2024-02-22 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_games_game_gamescore_finish_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="referral",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="gamescore",
            name="finish_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 2, 22, 2, 1, 9, 649277)
            ),
        ),
    ]
